version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - neo4j
      - mongodb
      - cassandra
    env_file:
      - .env

  postgres:
    build:
      context: ./docker
      dockerfile: Dockerfile.postgres
    env_file:
      - .env-templates/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    build:
      context: ./docker
      dockerfile: Dockerfile.neo4j
    env_file:
      - .env-templates/neo4j.env
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  mongodb:
    build:
      context: ./docker
      dockerfile: Dockerfile.mongodb
    env_file:
      - .env-templates/mongodb.env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  cassandra:
    build:
      context: ./docker
      dockerfile: Dockerfile.cassandra
    env_file:
      - .env-templates/cassandra.env
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  postgres_data:
  neo4j_data:
  mongo_data:
  cassandra_data: