version: '3.8'
services:
  example-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true
