# Dockerfile.neo4j
FROM neo4j:5.14
COPY ./init-scripts/neo4j/*.cypher /docker-entrypoint-initdb.d/
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
    CMD wget http://localhost:7474 || exit 1
