# Dockerfile.mongodb
FROM mongo:7.0
COPY ./init-scripts/mongodb/*.js /docker-entrypoint-initdb.d/
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
    CMD mongosh --eval 'db.runCommand("ping").ok' localhost:27017/test